"""
Django settings for WebsiteSecurityAnalyser project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import mimetypes
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8z8-d97l$_!8yath5=$$%*id^jtc&z*kxc%aex410k#-9bedul'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_cleanup.apps.CleanupConfig',
    'Account',
    'Main',
    'Analyser'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WebsiteSecurityAnalyser.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebsiteSecurityAnalyser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'wsa'),
        'USER': os.environ.get('MYSQL_USER', 'wsa'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'wsa'),
        'HOST': os.environ.get('MYSQL_DATABASE_HOST', 'db'),
        'PORT': os.environ.get('MYSQL_DATABASE_PORT', 3306),
        'default-character-set': "utf8",
        'OPTIONS': {
            'init_command': 'SET default_storage_engine=INNODB',
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',

    'PAGE_SIZE': 5,
}


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
JS_VERSION = "1.4"
STATIC_URL = '/static/'
MEDIA_URL = '/files/' + JS_VERSION + "/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/files/' + JS_VERSION)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_VENDOR = '/vendor/'
STATIC_VENDOR_ROOT = os.path.join(BASE_DIR, 'static/vendor')
AUTH_USER_MODEL = 'Account.User'
parent_dir = os.path.abspath(os.path.dirname(__file__) + '/..')


# smtp data leapswitch
EMAIL_HOST = 'mail.mails.geniobits.com'
EMAIL_USE_TLS = True
SERVER_EMAIL = 'casinoroll@mails.geniobits.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'casinoroll@mails.geniobits.com'
EMAIL_HOST_PASSWORD = 'tMMzc=$d#F;X'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'casinoroll@mails.geniobits.com'
BASE_DOMAIN = "localhost"
BASE_URL = "http://" + BASE_DOMAIN + "/"

AWS_ACCESS_KEY_ID = 'GIFQMG2V54XBFNDPV5ZQ'
AWS_SECRET_ACCESS_KEY = 'TPvVvJyoA1FsdW0AXHytvX89dxgOQdA4pFQ9fYlTirY'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = 'geniobits-372ced2e-8bfe-40ad-b8d8-1fb2b06c044d'
AWS_S3_ENDPOINT_URL = 'https://nyc3.digitaloceanspaces.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
S3_URL = "https://geniobits-372ced2e-8bfe-40ad-b8d8-1fb2b06c044d.nyc3.digitaloceanspaces.com"
AWS_S3_CUSTOM_DOMAIN = 'geniobits-372ced2e-8bfe-40ad-b8d8-1fb2b06c044d.nyc3.cdn.digitaloceanspaces.com'
STATIC_URL_CDN = "https://" + AWS_S3_CUSTOM_DOMAIN + "/static"
# STATIC_URL_CDN = ""
AWS_S3_FILE_OVERWRITE = False


mimetypes.add_type("text/css", ".css", True)
X_FRAME_OPTIONS = 'ALLOW-FROM http://localhost:3000/'

BROKER_URL = 'redis://redis:6379/'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


facebook_url = ""
twitter_url = ""
linkdln_url = ""
instagram_url = ""
email = ""
address = ""
app_url = ""
APP_NAME = "WSA"
APP_SMS_HASH = "#123123"
ADMIN_SITE_TITLE = "WSA Admin"
ADMIN_SITE_HEADER = "WSA Admin"
VIRUS_TOTAL_KEY = "3b19a36f8cd10e8c28b201d6bf618b2c999f4dd5534fa5645aaa34dc54f22cfd"
GOOGLE_SAFE_BROWSING_KEY = "AIzaSyCcYzRZroIZoq2qdW3tpiSZ3oTDFiRto4U"